### ISSUE TITLE
package versions / conda environment? [help]

### ISSUE THREAD

**Issue by PeterMitrano** [Fzaero/BRDPN#1]
Hello, I'm a PhD student at the university of michigain. I'm interested in reproducing the results of your cylinder pushing experiments, but can't figure out how to get a working python env for this project. Can you say which version of python, tensorflow, keras, and whatever else important you use?

I tried python 2.7 with tf 1.10.0 and keras 2.3.1 but clearly they don't match because I get errors internal to keras.

**Comment by Fzaero** [comment]
I think they were tf1.13.1 and Keras 2.2.4. If there are still errors with these versions, can you post those as well?

**Comment by PeterMitrano** [comment]
Interesting... it doesn't seem to work

```
$ conda create -n brdpn3 tensorflow=1.13.1 keras=2.2.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
```

If you used conda, you could try exporting the environment.yml file? Also, could you confirm what MSE numbers I should get if I run the Physics_Predictor_fixed notebook? For the output of cell [9] I got the following:

```
mse-pos: -0.969978117785957
mse-vel: -10.391441959576596
mse-pos: -4.313840778171972
mse-vel: -13.802156746120167
mse-pos: -0.8820940510485938
mse-vel: -10.353931362187321
```

but those numbers seem impossible -- they're negative, and very large?

**Comment by Fzaero** [comment]
I don't have this repository on my computer anymore, I'll check it when I can. It should also be python=2.7 maybe that may have caused the issues (I used python 2.7 with tensorflow=1.13.1 keras=2.2.4 recently, I think they should work). When I can, I will try to upload an environment.yml, will then make an update on this issue.

One thing I can think of is that if you receive an error with cudnnLSTM, it may have to do with tensorflow-gpu vs tensorflow issue. You may need to install tensorflow with tensorflow-gpu=1.13.1 

Errors are not negative, but since they tend to get very small, so they are outputted as np.log(error).

**Comment by PeterMitrano** [comment]
I have found a solution using the anaconda channel, so this works:

```conda create -n brdpn_env tensorflow-gpu=1.13.1 keras=2.2.4 -c anaconda```

I'll close this issue once I confirm I can run some of the Notebooks successfully

**Comment by Fzaero** [comment]
> I have found a solution using the anaconda channel, so this works:
> 
> `conda create -n brdpn_env tensorflow-gpu=1.13.1 keras=2.2.4 -c anaconda`
> 
> I'll close this issue once I confirm I can run some of the Notebooks successfully

Hope your solution works. My current work laptop does not have a GPU, because of that I was a bit limited. If your solution does not work, please do not hesitate to reopen the issue. I will have more time to check on this issue over this weekend.
